package ppm.backend.model;

public enum Currency {
  AFN,ALL,DZD,ARS,AMD,AUD,AZN,BSD,BHD,BDT,BBD,BYN,BEF,BZD,
  XOF,BMD,BTN,BOB,BAM,BWP,BRL,BND,BGN,BIF,KHR,XAF,CAD,CVE,
  KYD,COP,KMF,CDF,CRC,HRK,CUP,CZK,DKK,DJF,XCD,DOP,EGP,ERN,
  EEK,ETB,EUR,FJD,FIM,FRF,GMD,GEL,GHS,GIP,GTQ,GNF,GYD,HTG,
  HNL,HKD,HUF,ISK,INR,IDR,IRR,IQD,IEP,ILS,ITL,JMD,JPY,JOD,
  KZT,KES,KID,KWD,KGS,LAK,LVL,LBP,LSL,LRD,LYD,LTL,LU,MKD,
  MGA,MWK,MYR,MVR,MUR,MXN,MDL,MNT,MAD,MZN,MMK,NAD,NPR,ANG,
  NZD,NIO,NGN,KPW,NOK,OMR,PKR,PAB,PGK,PYG,PEN,PHP,PLN,QAR,
  RON,RUB,RWF,SHP,SVC,WST,STN,SAR,RSD,SCR,SLL,SGD,SBD,SOS,
  ZAR,KRW,SSP,ESP,LKR,SDG,SRD,SZL,SEK,CHF,SYP,TJS,TZS,THB,
  TOP,TTD,TND,TRY,TMT,UGX,UAH,AED,USD,UYU,UZS,VUV,VES,VND,
  YER,ZMW,ZWL;
}
